name: 'ArmorCode Release Gate'
description: 'Integrates ArmorCode release gates into your GitHub workflows to enforce security policies'
author: 'ArmorCode'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  product:
    description: 'ArmorCode product name'
    required: true
  subProduct:
    description: 'ArmorCode sub-product name'
    required: true
  env:
    description: 'Environment (e.g., production, staging)'
    required: false
    default: 'Production'
  mode:
    description: 'Mode of operation - "block" will fail the workflow, "warn" will only print warnings'
    required: false
    default: 'block'
  additionalAQLFilters:
    description: 'Additional AQL query parameters'
    required: false
    default: ''
  armorcodeAPIToken:
    description: 'ArmorCode API token'
    required: true
  maxRetries:
    description: 'Maximum number of retries for checking release gate status'
    required: false
    default: '5'
  armorcodeHost:
    description: 'ArmorCode API URL'
    required: false
    default: 'https://app.armorcode.com'
  github-token:
    description: 'GitHub token for posting PR comments'
    permissions:
      pull-requests: write
      contents: read
    required: false
    default: ${{ github.token }}  

runs:
  using: 'node20'
  main: 'dist/index.js'
